"""Pinecone vector database for historical events and ingested news.

Embeddings are generated by Pinecone's hosted model, so nothing is downloaded
locally. Without PINECONE_API_KEY, or if Pinecone is unreachable, event search
falls back to the local TF-IDF ranking and reports that it did.

Check a new key with:  uv run python -m app.tools.vector_store
"""

import hashlib
import os
import threading
import time

from app.tools.events import find_similar_events, load_events

EVENTS_NAMESPACE = "events"
NEWS_NAMESPACE = "news"
TEXT_FIELD = "chunk_text"
UPSERT_BATCH = 90
REQUEST_TIMEOUT_SECONDS = 6.0

PINECONE = "pinecone"
LOCAL = "local"

_lock = threading.Lock()
_state: dict = {"index": None, "ready": False, "error": None, "events_indexed": 0,
                "news_indexed": 0, "last_news_upsert_ms": None, "last_search_ms": None}


def enabled() -> bool:
    return bool(os.getenv("PINECONE_API_KEY"))


def _settings() -> dict:
    return {
        "name": os.getenv("PINECONE_INDEX", "market-intel"),
        "cloud": os.getenv("PINECONE_CLOUD", "aws"),
        "region": os.getenv("PINECONE_REGION", "us-east-1"),
        "model": os.getenv("PINECONE_EMBED_MODEL", "multilingual-e5-large"),
    }


def _event_record(event: dict) -> dict:
    return {
        "_id": event["id"],
        TEXT_FIELD: f'{event["title"]}. {event["description"]} {event["tags"]}',
        "type": event["type"],
        "date": event["date"],
        "title": event["title"],
    }


def warm_up() -> bool:
    """Create the index if needed and load the event corpus. Safe to call twice."""
    if not enabled():
        return False
    with _lock:
        if _state["ready"]:
            return True
        try:
            from pinecone import Pinecone

            settings = _settings()
            client = Pinecone(api_key=os.environ["PINECONE_API_KEY"])
            if not client.has_index(settings["name"]):
                client.create_index_for_model(
                    name=settings["name"],
                    cloud=settings["cloud"],
                    region=settings["region"],
                    embed={"model": settings["model"], "field_map": {"text": TEXT_FIELD}},
                )
            index = client.index(name=settings["name"])
            records = [_event_record(e) for e in load_events()]
            for start in range(0, len(records), UPSERT_BATCH):
                index.upsert_records(namespace=EVENTS_NAMESPACE, records=records[start:start + UPSERT_BATCH])
            _state.update(index=index, ready=True, error=None, events_indexed=len(records))
        except Exception as exc:  # optional service: any failure means "use the fallback"
            _state.update(ready=False, error=f"{type(exc).__name__}: {exc}")
        return _state["ready"]


def warm_up_in_background() -> None:
    if enabled():
        threading.Thread(target=warm_up, daemon=True).start()


def search_events(query: str, event_type: str | None = None, limit: int = 6) -> tuple[list[dict], str]:
    """Past events most similar to the query, and which backend ranked them.

    A question with no identified event type and no shared vocabulary with any
    event is treated as a general question and matches nothing; a vector search
    would otherwise always return its nearest neighbours, however unrelated.
    """
    local = find_similar_events(query, event_type, limit)
    if not _state["ready"] or not local:
        return local, LOCAL

    by_id = {e["id"]: e for e in load_events()}
    try:
        started = time.perf_counter()
        response = _state["index"].search(
            namespace=EVENTS_NAMESPACE,
            top_k=limit,
            inputs={"text": query},
            filter={"type": {"$eq": event_type}} if event_type else None,
            fields=["title"],
            timeout=REQUEST_TIMEOUT_SECONDS,
        )
        _state["last_search_ms"] = round((time.perf_counter() - started) * 1000)
        hits = [
            {**by_id[hit.id], "similarity": round(float(hit.score), 2)}
            for hit in response.result.hits
            if hit.id in by_id
        ]
    except Exception as exc:
        _state["error"] = f"{type(exc).__name__}: {exc}"
        return local, LOCAL
    # Freshly upserted records take a moment to become searchable.
    return (hits, PINECONE) if hits else (local, LOCAL)


def _upsert_news(items: list[dict]) -> None:
    records = [
        {
            "_id": hashlib.sha1((item.get("url") or item["title"]).encode()).hexdigest(),
            TEXT_FIELD: item["title"],
            "source": item.get("source") or "",
            "published_at": item.get("published_at") or "",
        }
        for item in items
    ]
    try:
        started = time.perf_counter()
        for start in range(0, len(records), UPSERT_BATCH):
            _state["index"].upsert_records(
                namespace=NEWS_NAMESPACE,
                records=records[start:start + UPSERT_BATCH],
                timeout=REQUEST_TIMEOUT_SECONDS,
            )
        _state["last_news_upsert_ms"] = round((time.perf_counter() - started) * 1000)
        _state["news_indexed"] += len(records)
    except Exception as exc:
        _state["error"] = f"{type(exc).__name__}: {exc}"


def index_news(items: list[dict]) -> None:
    """Embed and index headlines without delaying the caller."""
    if _state["ready"] and items:
        threading.Thread(target=_upsert_news, args=(items,), daemon=True).start()


def status() -> dict:
    return {
        "backend": PINECONE if _state["ready"] else LOCAL,
        "configured": enabled(),
        "index": _settings()["name"] if enabled() else None,
        "embedding_model": _settings()["model"] if enabled() else None,
        **{k: _state[k] for k in ("events_indexed", "news_indexed", "last_news_upsert_ms",
                                  "last_search_ms", "error")},
    }


if __name__ == "__main__":
    from dotenv import load_dotenv

    load_dotenv()
    if not enabled():
        raise SystemExit("PINECONE_API_KEY is not set in backend/.env")
    print("Connecting to Pinecone and loading events...")
    if not warm_up():
        raise SystemExit(f"Failed: {_state['error']}")
    print(f"Indexed {_state['events_indexed']} events. Waiting for them to become searchable...")
    question = "cyclone hitting Gujarat refineries"
    for _ in range(10):
        found, backend = search_events(question, "cyclone", 3)
        if backend == PINECONE:
            break
        time.sleep(3)
    print(f"Search backend: {backend} ({_state['last_search_ms']} ms)")
    for event in found:
        print(f'  {event["similarity"]:.2f}  {event["date"]}  {event["title"]}')
    if backend != PINECONE:
        raise SystemExit(f"Search did not use Pinecone. Last error: {_state['error']}")
