"""Live alerts for a portfolio: sudden price moves, elevated risk of one,
portfolio losses, concentration, negative news, weather and market stress.

Every number in an alert is computed here from live data and from the files
written by app.ml.train. Nothing is generated by a language model.
"""

import hashlib
import json
import math
from datetime import datetime, timezone
from functools import lru_cache
from pathlib import Path

import numpy as np

from app.ingestion.news import get_news
from app.ml.features import FEATURES, HORIZON, SHOCK_Z, abnormal_returns, risk_features
from app.ml.radar import radar_alerts
from app.risk import metrics
from app.tools import resolver
from app.tools import sentiment as sentiment_tool
from app.tools.market import NIFTY, get_history, get_macro, normalise_holdings

TRAINED_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "trained"
SEVERITY_ORDER = {"critical": 0, "warning": 1, "info": 2}
MAX_NEWS_ALERTS = 3
LARGE_POSITION = 0.15


@lru_cache(maxsize=None)
def _trained(name: str) -> dict | None:
    try:
        return json.loads((TRAINED_DIR / f"{name}.json").read_text())
    except (OSError, ValueError):
        return None


def _inr(amount: float) -> str:
    return f"₹{abs(amount):,.0f}"


def _pct(fraction: float, digits: int = 1) -> str:
    return f"{abs(fraction) * 100:.{digits}f}%"


def _alert(severity: str, category: str, key: str, title: str, detail: str,
           recommendation: str, basis: str, holding: str | None = None, hedge: dict | None = None) -> dict:
    return {
        "id": hashlib.sha1(f"{category}|{key}".encode()).hexdigest()[:12],
        "severity": severity, "category": category, "holding": holding,
        "title": title, "detail": detail, "recommendation": recommendation, "basis": basis,
        "hedge": hedge,
    }


def shock_probability(features: dict, model: dict) -> float:
    """Chance of a sudden move in the next sessions, from the trained weights."""
    score = model["intercept"] + sum(
        model["weights"][name] * (features[name] - model["mean"][name]) / model["std"][name]
        for name in model["features"]
    )
    return 1 / (1 + math.exp(-score))


# --------------------------------------------------------------------------- price and risk


def _price_alerts(positions: list[dict], closes, total: float) -> list[dict]:
    model = _trained("shock_model")
    alerts = []
    day = closes.index[-1].date().isoformat()
    for p in positions:
        days = risk_features(abnormal_returns(closes[p["ticker"]], closes[NIFTY]))
        last = days.iloc[-1]
        if any(math.isnan(last[name]) for name in FEATURES) or math.isnan(last["return"]):
            continue
        z, move, weight = float(last["z"]), float(last["return"]), p["value"] / total
        impact = p["value"] / (1 + move) * move  # rupee change on the day
        size_note = (f" It is {_pct(weight, 0)} of your portfolio, so the move changed its value by "
                     f"{_inr(impact)}." if weight >= LARGE_POSITION else "")

        if abs(z) >= SHOCK_Z:
            fell = z < 0
            history = (model or {}).get("after_a_sudden_move", {}).get("drops" if fell else "jumps")
            if history:
                share = history["kept_falling" if fell else "kept_rising"]
                pattern = (f"After {history['cases']:,} similar {'drops' if fell else 'jumps'} in NSE stocks since "
                           f"2023, the stock kept {'falling' if fell else 'rising'} against the market over the "
                           f"next {HORIZON} sessions {_pct(share, 0)} of the time, which is no better than a coin flip.")
            else:
                pattern = "No record of similar past moves is available."
            alerts.append(_alert(
                "critical" if fell and (abs(z) >= 3 or move <= -0.05) else "warning" if fell else "info",
                "price", f'{p["ticker"]}|{day}',
                f'{p["name"]} {"fell" if fell else "rose"} {_pct(move)} on {day}',
                f"That is {abs(z):.1f} times its usual daily move beyond the market.{size_note}",
                ("The size of a drop does not predict what comes next, so do not sell on the move alone. "
                 "Check the news for a cause; if the reason is company-specific and lasting, review the position."
                 if fell else
                 "A jump does not predict further gains. No action needed unless the position has grown "
                 "beyond the share you want."),
                pattern, p["name"],
            ))
            continue

        if model:
            probability = shock_probability({name: float(last[name]) for name in FEATURES}, model)
            if probability >= model["elevated_cutoff"]:
                test = model["test"]
                alerts.append(_alert(
                    "warning" if weight >= LARGE_POSITION else "info",
                    "risk", f'{p["ticker"]}|{day}',
                    f'{p["name"]}: higher chance of a sudden move this week',
                    f"The risk model scores it {_pct(probability, 0)}, inside its highest-risk tenth of days."
                    f"{' It is ' + _pct(weight, 0) + ' of your portfolio.' if weight >= LARGE_POSITION else ''}",
                    "The move could be up or down. Avoid adding to the position this week, and if a loss here "
                    "would hurt, ask the assistant to size a hedge.",
                    f"On days scored this high in testing ({test['period']}), a sudden move followed "
                    f"{_pct(test['rate_when_elevated'], 0)} of the time, against {_pct(test['base_rate'], 0)} "
                    f"on a typical day. Model AUC {test['auc']}.",
                    p["name"],
                ))
    return alerts


def _portfolio_alert(positions: list[dict], closes, total: float) -> list[dict]:
    weights = {p["ticker"]: p["value"] / total for p in positions}
    returns = metrics.portfolio_returns(metrics.daily_returns(closes), weights)
    var = metrics.historical_var(returns)
    if var is None or returns.empty:
        return []
    today = float(returns.iloc[-1])
    if today > -var[0]:
        return []
    day = returns.index[-1].date().isoformat()
    return [_alert(
        "critical", "portfolio", day,
        f"Portfolio fell {_pct(today)} on {day}",
        f"That is a loss of about {_inr(today * total)}, beyond the 1-day 95% VaR of {_pct(var[0])} "
        f"({_inr(var[0] * total)}).",
        "A loss this size is expected about one day in twenty. See which holdings drove it in the alerts "
        "below before changing anything.",
        f"Historical simulation over the last {len(returns)} sessions at today's weights.",
    )]


def _concentration_alert(positions: list[dict], total: float) -> list[dict]:
    benchmark = _trained("concentration_benchmark")
    if not benchmark or not positions:
        return []
    largest = max(positions, key=lambda p: p["value"])
    share = largest["value"] / total * 100
    if share <= benchmark["p90"]:
        return []
    percentile = int(np.searchsorted(benchmark["percentiles"], share, side="right")) - 1
    return [_alert(
        "warning", "concentration", largest["ticker"],
        f'{largest["name"]} is {share:.0f}% of your portfolio',
        f"One holding carries most of your risk: a 10% fall in it would cost about {_inr(largest['value'] * 0.1)}.",
        "Consider spreading new money into other holdings, or trimming this one, until no single position "
        "dominates the portfolio.",
        f"More concentrated than {min(percentile, 99)}% of {benchmark['portfolio_quarters']:,} institutional "
        f"portfolio-quarters ({benchmark['managers']} managers, SEC 13F filings). Their median largest "
        f"position is {benchmark['median']:.0f}%.",
        largest["name"],
    )]


# --------------------------------------------------------------------------- news, weather, market


def _name_keys(holding: dict) -> list[str]:
    """Lower-case phrases that identify the company in a headline."""
    words = resolver.clean_name(holding["name"]).lower().split()
    keys = [" ".join(words[:2])] if len(words) >= 2 else words
    symbol = holding["ticker"].split(".")[0].lower()
    if len(symbol) >= 4:
        keys.append(symbol)
    return [k for k in keys if len(k) >= 4]


def _news_alerts(positions: list[dict]) -> list[dict]:
    names = [p["name"] for p in positions[:8]]
    if not names:
        return []
    items = get_news(" OR ".join(f'"{n}"' for n in names) + " when:3d", 20)
    if not items:
        return []
    negative_cutoff = sentiment_tool.cutoffs()[1]
    scores = sentiment_tool.score_many([item["title"] for item in items])
    alerts = []
    for item, score in sorted(zip(items, scores), key=lambda pair: pair[1]):
        if score > negative_cutoff or len(alerts) >= MAX_NEWS_ALERTS:
            break
        title = item["title"].lower()
        holding = next((p for p in positions if any(key in title for key in _name_keys(p))), None)
        if holding is None:
            continue  # the search matched loosely; the headline is not about a holding
        alerts.append(_alert(
            "warning", "news", item.get("url") or item["title"],
            f'Negative news on {holding["name"]}',
            f'"{item["title"]}" ({item.get("source") or "news"})',
            "Read the story before acting. One negative headline is not a reason to sell; a string of them "
            "about the same problem is worth reviewing the position.",
            f"Sentiment score {score:+.2f} from {sentiment_tool.backend()}; headlines at or below "
            f"{negative_cutoff:+.2f} are treated as negative.",
            holding["name"],
        ))
    return alerts


def _market_alert() -> list[dict]:
    from app.agents.nodes import _macro_flags

    indicators, _ = get_macro()
    flags = _macro_flags(indicators)
    if not flags:
        return []
    return [_alert(
        "info", "market", ",".join(flags),
        "Market stress: " + ", ".join(flags),
        "; ".join(f'{i["label"]} {i["value"]:,.2f} ({i["change_1m_pct"]:+.1f}% in a month)' for i in indicators) + ".",
        "Sudden moves in individual holdings are more likely in stressed markets. Avoid large new positions "
        "until conditions settle.",
        "Yahoo Finance; flags are fixed thresholds on the one-month changes.",
    )]


# --------------------------------------------------------------------------- entry point


def _alt_data_alerts(positions: list[dict], closes, scenario: str | None) -> list[dict]:
    """Weather and geopolitical signals with exposure, pricing and a sized hedge."""
    return [_alert(a["severity"], a["category"], a["key"], a["title"], a["detail"], a["recommendation"],
                   a["basis"], hedge=a["hedge"]) for a in radar_alerts(positions, closes, scenario)]


def build_alerts(raw_holdings: list[dict] | None, scenario: str | None = None) -> dict:
    holdings, source = normalise_holdings(raw_holdings)
    closes, price_source = get_history([h["ticker"] for h in holdings])
    alerts: list[dict] = []
    unavailable: list[str] = []
    as_of = None

    if closes is None:
        unavailable.append("prices")
    else:
        latest = closes.iloc[-1]
        positions = []
        for h in holdings:
            price = latest.get(h["ticker"])
            if price is not None and not math.isnan(price):
                positions.append({**h, "value": float(price) * h["units"]})
        positions.sort(key=lambda p: -p["value"])
        total = sum(p["value"] for p in positions)
        as_of = closes.index[-1].date().isoformat()
        if total > 0:
            for build in (lambda: _alt_data_alerts(positions, closes, scenario),
                          lambda: _portfolio_alert(positions, closes, total),
                          lambda: _price_alerts(positions, closes, total),
                          lambda: _concentration_alert(positions, total),
                          lambda: _news_alerts(positions)):
                try:
                    alerts += build()
                except Exception:  # one failing check must not hide the others
                    unavailable.append("a check failed")

    for name, build in (("market", _market_alert),):
        try:
            alerts += build()
        except Exception:
            unavailable.append(name)

    # A drill is something the user just asked to see, so it leads; then most severe first.
    alerts.sort(key=lambda a: (not (a["hedge"] or {}).get("drill", False), SEVERITY_ORDER[a["severity"]]))
    model = _trained("shock_model")
    return {
        "alerts": alerts,
        "portfolio_source": source,
        "prices_as_of": as_of,
        "price_source": price_source,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "unavailable": sorted(set(unavailable)),
        "risk_model": {"auc": model["test"]["auc"], "tested_on": model["test"]["period"],
                       "trained_on": model["trained_on"]} if model else None,
    }
