"""Live alerts for a portfolio: sudden price moves, a raised chance of a sharp
fall, portfolio losses, concentration, negative news, weather and market stress.
Each alert carries a solution: one sized action and the steps to take.

Every number in an alert is computed here from live data and from the files
written by app.ml.train. Nothing is generated by a language model.
"""

import hashlib
import json
import math
from datetime import datetime, timezone
from functools import lru_cache
from pathlib import Path

import numpy as np

from app.ingestion.news import get_news, names_holding
from app.ml import impact, solutions
from app.ml.features import FALL_SIZE, FEATURES, HORIZON, SHOCK_Z, abnormal_returns, risk_features
from app.ml.radar import PRICED_SESSIONS, radar_alerts
from app.risk import metrics
from app.tools import sentiment as sentiment_tool
from app.tools.market import NIFTY, get_history, get_macro, normalise_holdings
from app.agents.state import inr as indian_rupees

TRAINED_DIR = Path(__file__).resolve().parent.parent.parent / "data" / "trained"
SEVERITY_ORDER = {"critical": 0, "warning": 1, "info": 2}
MAX_NEWS_ALERTS = 3
LARGE_POSITION = 0.15


@lru_cache(maxsize=None)
def _trained(name: str) -> dict | None:
    try:
        return json.loads((TRAINED_DIR / f"{name}.json").read_text())
    except (OSError, ValueError):
        return None


def _inr(amount: float) -> str:
    """Rupees without a sign, in Indian digit grouping."""
    return indian_rupees(abs(amount))


def _pct(fraction: float, digits: int = 1) -> str:
    return f"{abs(fraction) * 100:.{digits}f}%"


def _step(title: str, finding: str, method: str | None = None) -> dict:
    """One step of an alert's evidence trail: what was found, and how."""
    return {"title": title, "finding": finding, "method": method}


def _alert(severity: str, category: str, key: str, title: str, detail: str, solution: dict, basis: str,
           holding: str | None = None, hedge: dict | None = None, recommendation: str | None = None,
           trail: list[dict | None] | None = None) -> dict:
    # The trail runs from the signal to the decision; the decision is always its last step.
    steps = [s for s in trail or [] if s] + [_step("How the action was chosen", solution["why"])]
    return {
        "id": hashlib.sha1(f"{category}|{key}".encode()).hexdigest()[:12],
        "severity": severity, "category": category, "holding": holding,
        "title": title, "detail": detail, "solution": solution,
        "recommendation": recommendation or solutions.text(solution), "basis": basis,
        "hedge": hedge, "trail": steps,
    }


def shock_probability(features: dict, model: dict) -> float:
    """Chance of a sudden move in the next sessions, from the trained weights."""
    score = model["intercept"] + sum(
        model["weights"][name] * (features[name] - model["mean"][name]) / model["std"][name]
        for name in model["features"]
    )
    return 1 / (1 + math.exp(-score))


# --------------------------------------------------------------------------- price and risk


def _annual_volatility(returns, ticker: str) -> float:
    return float(returns[ticker].std()) * math.sqrt(metrics.TRADING_DAYS_1Y)


def _implied_ratio() -> float:
    """How much more volatility options have priced than the market then delivered."""
    return (_trained("hedge_cost") or {}).get("implied_over_realised", {}).get("median", 1.0)


def _protect(p: dict, score: dict, returns, total: float) -> dict:
    return solutions.protect_or_trim(p, score, _annual_volatility(returns, p["ticker"]), total, _implied_ratio(),
                                     impact.model()["fall"]["base_rate"])


ABNORMAL_METHOD = ("Abnormal return = the stock's return minus beta x the Nifty 50's return, with beta measured "
                   "over 250 sessions, divided by the standard deviation of the last 60 sessions. Yahoo Finance "
                   "closing prices.")


def _impact_step(score: dict | None) -> dict:
    """What the impact model says about one holding, or that it could not score it."""
    trained = impact.model()
    if not score or not trained:
        return _step("What the impact model says",
                     "The model could not score this holding: its macro inputs were unavailable or the holding has "
                     "too little price history.")
    fall = trained["fall"]
    return _step(
        "What the impact model says",
        f'Chance of a fall of {_pct(FALL_SIZE, 0)} or more in the next {HORIZON} sessions: {_pct(score["fall"], 0)}. '
        f'The model flags a holding at {_pct(fall["elevated_cutoff"], 0)} or more, so this one is '
        f'{"flagged" if score["elevated"] else "not flagged"}. Its {HORIZON}-day downside is '
        f'-{_pct(score["downside"])}, against a usual -{_pct(score["usual_downside"])}.',
        f"LightGBM trees on price history, India VIX, Brent, USD/INR, sector and weather alert days. AUC "
        f"{fall['auc']} on {trained['test_period']}; price history alone {fall['auc_by_data_used']['price history']}.")


def _today(positions: list[dict], closes) -> dict[str, dict]:
    """Per ticker: today's move, how unusual it was beyond the market, and the old model's inputs."""
    today = {}
    for p in positions:
        last = risk_features(abnormal_returns(closes[p["ticker"]], closes[NIFTY])).iloc[-1]
        if not math.isnan(last["z"]) and not math.isnan(last["return"]):
            today[p["ticker"]] = {"z": float(last["z"]), "move": float(last["return"]),
                                  "features": {name: float(last[name]) for name in FEATURES}}
    return today


def _price_alerts(positions: list[dict], closes, total: float, today: dict, scores: dict | None,
                  returns) -> list[dict]:
    shock_model, impact_model = _trained("shock_model"), impact.model()
    alerts = []
    day = closes.index[-1].date().isoformat()
    for p in positions:
        seen = today.get(p["ticker"])
        if seen is None:
            continue
        z, move, weight = seen["z"], seen["move"], p["value"] / total
        score = (scores or {}).get(p["ticker"])
        impact_rupees = p["value"] / (1 + move) * move  # rupee change on the day
        size_note = (f" It is {_pct(weight, 0)} of your portfolio, so the move changed its value by "
                     f"{_inr(impact_rupees)}." if weight >= LARGE_POSITION else "")

        if abs(z) >= SHOCK_Z:
            fell = z < 0
            history = (shock_model or {}).get("after_a_sudden_move", {}).get("drops" if fell else "jumps")
            if history:
                share = history["kept_falling" if fell else "kept_rising"]
                pattern = (f"After {history['cases']:,} similar {'drops' if fell else 'jumps'} in NSE stocks since "
                           f"2023, the stock kept {'falling' if fell else 'rising'} against the market over the "
                           f"next {HORIZON} sessions {_pct(share, 0)} of the time, which is no better than a coin flip.")
            else:
                pattern = "No record of similar past moves is available."
            if fell and score and (score["elevated"] or weight >= LARGE_POSITION):
                solution = _protect(p, score, returns, total)
            else:
                solution = solutions.hold_after_move(
                    p["name"], fell, pattern,
                    solutions.stop_price(p["price"], score["downside"]) if score else None,
                    f"It is now {_pct(weight, 0)} of the portfolio; trim it if that is more than you want in one "
                    f"holding." if weight >= LARGE_POSITION else None)
            alerts.append(_alert(
                "critical" if fell and (abs(z) >= 3 or move <= -0.05) else "warning" if fell else "info",
                "price", f'{p["ticker"]}|{day}',
                f'{p["name"]} {"fell" if fell else "rose"} {_pct(move)} on {day}',
                f"That is {abs(z):.1f} times its usual daily move beyond the market.{size_note}",
                solution, pattern, p["name"],
                trail=[
                    _step("What was detected",
                          f'{p["name"]} {"fell" if fell else "rose"} {_pct(move)} on {day}. With the market\'s part '
                          f"removed, that is {abs(z):.1f} times the standard deviation of its recent daily moves.",
                          ABNORMAL_METHOD),
                    _step("Why it is an alert",
                          f"Any move of {SHOCK_Z:.0f} standard deviations or more is flagged. A fall is critical at "
                          f"3 or more, or at a loss of 5% or more; otherwise it is a warning. A rise is for "
                          f"information only."
                          + (f" The holding is {_pct(weight, 0)} of the portfolio; {_pct(LARGE_POSITION, 0)} or more "
                             f"counts as a large position." if weight >= LARGE_POSITION else "")),
                    _step("What similar moves did next", pattern,
                          "Counted across NSE stocks from 2023 onwards, the years the risk model was tested on."),
                    _impact_step(score) if fell else None,
                ],
            ))
            continue

        if score and score["elevated"]:
            solution = _protect(p, score, returns, total)
            fall = impact_model["fall"]
            alerts.append(_alert(
                "warning" if weight >= LARGE_POSITION or solution["action"] in ("hedge", "trim") else "info",
                "risk", f'{p["ticker"]}|{day}',
                f'{p["name"]}: {_pct(score["fall"], 0)} chance of a {_pct(FALL_SIZE, 0)}+ fall this week',
                f"The impact model puts today among its highest-risk days for this holding. Its {HORIZON}-day "
                f'downside is {_inr(score["downside"] * p["value"])} (-{_pct(score["downside"])}), against a usual '
                f'{_inr(score["usual_downside"] * p["value"])} (-{_pct(score["usual_downside"])}).'
                f"{' It is ' + _pct(weight, 0) + ' of your portfolio.' if weight >= LARGE_POSITION else ''}",
                solution,
                f"On days scored this high in testing ({impact_model['test_period']}), a fall of "
                f"{_pct(FALL_SIZE, 0)} or more followed {_pct(fall['rate_when_elevated'], 0)} of the time, against "
                f"{_pct(fall['rate_otherwise'], 0)} otherwise. LightGBM on price, macro, sector and weather data: "
                f"AUC {fall['auc']}; price history alone {fall['auc_by_data_used']['price history']}.",
                p["name"],
                trail=[
                    _impact_step(score),
                    _step("What flagged days did in testing",
                          f"On the days the model flagged, a fall of {_pct(FALL_SIZE, 0)} or more followed "
                          f"{_pct(fall['rate_when_elevated'], 0)} of the time, against {_pct(fall['rate_otherwise'], 0)} "
                          f"on other days. Most flagged days are still followed by no sharp fall.",
                          f"Measured on {impact_model['test_days']:,} stock-days from {impact_model['test_period']}, "
                          f"which the model never saw in training."),
                ],
            ))
        elif scores is None and shock_model:
            # The impact model's inputs are unavailable, so the price-only model stands in.
            probability = shock_probability(seen["features"], shock_model)
            if probability >= shock_model["elevated_cutoff"]:
                test = shock_model["test"]
                alerts.append(_alert(
                    "warning" if weight >= LARGE_POSITION else "info",
                    "risk", f'{p["ticker"]}|{day}',
                    f'{p["name"]}: higher chance of a sudden move this week',
                    f"The risk model scores it {_pct(probability, 0)}, inside its highest-risk tenth of days."
                    f"{' It is ' + _pct(weight, 0) + ' of your portfolio.' if weight >= LARGE_POSITION else ''}",
                    solutions.solution("watch", f'Avoid adding to {p["name"]} this week', [
                        "The move could be up or down, so this is a reason for caution, not a reason to sell.",
                        "If a loss here would hurt, ask the assistant to size a hedge."],
                        why="Rule: this model predicts the size of a move, not its direction, so it can justify "
                            "caution but not a sale or a hedge."),
                    f"On days scored this high in testing ({test['period']}), a sudden move followed "
                    f"{_pct(test['rate_when_elevated'], 0)} of the time, against {_pct(test['base_rate'], 0)} "
                    f"on a typical day. Model AUC {test['auc']}. Macro data was unavailable, so the price-only "
                    f"model was used.",
                    p["name"],
                    trail=[
                        _step("What was detected",
                              f"The price-only risk model scores {_pct(probability, 0)} for a sudden move in the "
                              f"next {HORIZON} sessions; it flags scores of {_pct(shock_model['elevated_cutoff'], 0)} "
                              f"or more.",
                              "Logistic regression on six price features. The impact model was not used because "
                              "its macro data was unavailable."),
                        _step("What flagged days did in testing",
                              f"A sudden move followed {_pct(test['rate_when_elevated'], 0)} of the time, against "
                              f"{_pct(test['base_rate'], 0)} on a typical day.", f"Tested on {test['period']}."),
                    ],
                ))
    return alerts


def _portfolio_alert(positions: list[dict], closes, total: float, returns, beta: float | None,
                     vix: float | None) -> list[dict]:
    weights = {p["ticker"]: p["value"] / total for p in positions}
    daily = metrics.portfolio_returns(returns, weights)
    var = metrics.historical_var(daily)
    if var is None or daily.empty:
        return []
    today = float(daily.iloc[-1])
    if today > -var[0]:
        return []
    day = daily.index[-1].date().isoformat()
    loss = -today * total
    market_today = float(returns[NIFTY].iloc[-1])
    from_market = max(-(beta or 0.0) * market_today * total, 0.0)
    figures = [("Loss on the day", _inr(loss)), ("1-day 95% VaR", _inr(var[0] * total)),
               ("Part explained by the Nifty", _inr(from_market))]
    usual = "A loss this size is expected about one day in twenty, so one bad day is not a reason to sell."
    if beta and from_market >= 0.5 * loss:
        solution = solutions.index_hedge(
            total, beta, vix, "Mostly a market move; hedge the index only if you expect more",
            f"About {_inr(from_market)} of the {_inr(loss)} loss came from the Nifty's {_pct(market_today)} fall. {usual}")
        solution["figures"] = [{"label": label, "value": value} for label, value in figures] + solution["figures"][2:]
    else:
        solution = solutions.solution(
            "review", "Mostly stock-specific; review the holdings that fell",
            [f"Only {_inr(from_market)} of the {_inr(loss)} loss came from the market, so an index hedge would "
             f"not have helped.",
             "The price alerts below name the holdings that drove it, each with its own action.", usual],
            figures,
            why=f"Rule: an index hedge is offered only when at least half of the loss came from the market. Here "
                f"the market explains {_inr(from_market)} of {_inr(loss)}, less than half, so the action is to "
                f"review the holdings that fell.")
    return [_alert(
        "critical", "portfolio", day,
        f"Portfolio fell {_pct(today)} on {day}",
        f"That is a loss of about {_inr(loss)}, beyond the 1-day 95% VaR of {_pct(var[0])} "
        f"({_inr(var[0] * total)}).",
        solution,
        f"Historical simulation over the last {len(daily)} sessions at today's weights.",
        trail=[
            _step("What was detected", f"The portfolio fell {_pct(today)} on {day}, a loss of about {_inr(loss)}.",
                  "Each holding's daily return weighted by its share of the portfolio today."),
            _step("Why it is an alert",
                  f"The 1-day 95% VaR is {_inr(var[0] * total)}: on 19 days out of 20 the loss should be smaller. "
                  f"Today's loss is larger, so it is flagged as critical.",
                  f"Historical simulation over the last {len(daily)} sessions at today's weights."),
            _step("Where the loss came from",
                  f"The Nifty 50 moved {market_today * 100:+.1f}% and the portfolio's beta is {beta:.2f}, so about "
                  f"{_inr(from_market)} of the loss is the market's and {_inr(max(loss - from_market, 0))} is "
                  f"specific to your holdings.",
                  "Market part = beta x Nifty 50 return x portfolio value.") if beta else None,
        ],
    )]


def _concentration_alert(positions: list[dict], total: float, returns=None) -> list[dict]:
    benchmark = _trained("concentration_benchmark")
    if not benchmark or not positions:
        return []
    largest = max(positions, key=lambda p: p["value"])
    share = largest["value"] / total * 100
    if share <= benchmark["p90"]:
        return []
    percentile = int(np.searchsorted(benchmark["percentiles"], share, side="right")) - 1
    target = benchmark["p90"] / 100

    var_before = var_after = None
    partners: list[tuple[str, float]] = []
    if returns is not None and largest["ticker"] in returns.columns:
        weights = {p["ticker"]: p["value"] / total for p in positions}
        before = metrics.historical_var(metrics.portfolio_returns(returns, weights))
        after = metrics.historical_var(metrics.portfolio_returns(returns, {**weights, largest["ticker"]: target}))
        if before and after:
            var_before, var_after = before[0], after[0]
        # Where the money could go: the holdings that move least with the one being cut.
        others = [p for p in positions if p is not largest and p["ticker"] in returns.columns]
        linked = [(p["name"], float(returns[p["ticker"]].corr(returns[largest["ticker"]]))) for p in others]
        partners = sorted((pair for pair in linked if not math.isnan(pair[1])), key=lambda pair: pair[1])[:2]
    return [_alert(
        "warning", "concentration", largest["ticker"],
        f'{largest["name"]} is {share:.0f}% of your portfolio',
        f"One holding carries most of your risk: a 10% fall in it would cost about {_inr(largest['value'] * 0.1)}.",
        solutions.rebalance(largest, target, total, var_before, var_after, partners),
        f"More concentrated than {min(percentile, 99)}% of {benchmark['portfolio_quarters']:,} institutional "
        f"portfolio-quarters ({benchmark['managers']} managers, SEC 13F filings). Their median largest "
        f"position is {benchmark['median']:.0f}%; the target is the level nine in ten of them stay under.",
        largest["name"],
        trail=[
            _step("What was detected",
                  f'{largest["name"]} is {share:.0f}% of the portfolio: {_inr(largest["value"])} of {_inr(total)}.',
                  "Latest closing price x units held, for every priced holding."),
            _step("Why it is an alert",
                  f"That is more concentrated than {min(percentile, 99)}% of {benchmark['portfolio_quarters']:,} "
                  f"institutional portfolio-quarters, whose median largest position is {benchmark['median']:.0f}%. "
                  f"The alert fires above their 90th percentile, {benchmark['p90']:.0f}%.",
                  f"Quarterly SEC 13F filings of {benchmark['managers']} managers."),
            _step("What the sale would change",
                  f"The 1-day 95% VaR falls from {_inr(var_before * total)} to {_inr(var_after * total)}."
                  + (" The holdings that move least with it are "
                     + " and ".join(f"{name} (correlation {value:.2f})" for name, value in partners) + "."
                     if partners else ""),
                  "Historical simulation with the holding cut to the target and the proceeds held as cash; "
                  "correlations of daily returns over the last 250 sessions.") if var_before and var_after else None,
        ],
    )]


# --------------------------------------------------------------------------- news, weather, market


def _sentiment_record() -> str | None:
    """How the sentiment scorer in use did on labelled sentences it had not seen."""
    key = "finbert" if sentiment_tool.backend() == sentiment_tool.FINBERT else "vader"
    record = (_trained("sentiment_eval") or {}).get(key, {})
    if "holdout_accuracy" not in record:
        return None
    return (f"On labelled financial sentences it had not seen, it gave the right label "
            f"{_pct(record['holdout_accuracy'], 0)} of the time (Financial PhraseBank).")


def _news_alerts(positions: list[dict], today: dict, scores: dict | None, returns, total: float) -> list[dict]:
    names = [p["name"] for p in positions[:8]]
    if not names:
        return []
    items = get_news(" OR ".join(f'"{n}"' for n in names) + " when:3d", 20)
    if not items:
        return []
    negative_cutoff = sentiment_tool.cutoffs()[1]
    scored = sentiment_tool.score_many([item["title"] for item in items])
    alerts = []
    for item, sentiment in sorted(zip(items, scored), key=lambda pair: pair[1]):
        if sentiment > negative_cutoff or len(alerts) >= MAX_NEWS_ALERTS:
            break
        holding = next((p for p in positions if names_holding(item["title"], p["name"], p["ticker"])), None)
        if holding is None:
            continue  # the search matched loosely; the headline is not about a holding
        seen, score = today.get(holding["ticker"]), (scores or {}).get(holding["ticker"])
        if seen is None:
            reaction = None
        elif seen["z"] <= -1:
            reaction = (f'The stock has already fallen {_pct(seen["move"])} today, {abs(seen["z"]):.1f} times its '
                        f"usual daily move beyond the market, so some of the news is in the price.")
        elif seen["z"] < 1:
            reaction = (f'The stock moved {seen["move"] * 100:+.1f}% today, inside its usual daily range, so the '
                        f"market has not reacted to the story so far.")
        else:
            reaction = f'The stock rose {_pct(seen["move"])} today despite the headline.'
        if score and score["elevated"]:
            solution = _protect(holding, score, returns, total)
            solution["steps"] = [s for s in (reaction, *solution["steps"]) if s]
        else:
            solution = solutions.solution(
                "review", f'Read the story on {holding["name"]} before trading',
                [reaction,
                 "If the problem is lasting (a regulatory action, a lost contract, a governance failure), cut the "
                 "position; if it is a one-day story, hold. One negative headline is not a reason to sell.",
                 f'Set a price alert at ₹{solutions.stop_price(holding["price"], score["downside"]):,.2f}; a close '
                 f"below it would be an unusually bad week." if score else None],
                why="Rule: a negative headline leads to a trade only when the impact model also flags the holding. "
                    "It does not here, so the action is to read the story and decide whether the problem is lasting.")
        alerts.append(_alert(
            "warning", "news", item.get("url") or item["title"],
            f'Negative news on {holding["name"]}',
            f'"{item["title"]}" ({item.get("source") or "news"})',
            solution,
            f"Sentiment score {sentiment:+.2f} from {sentiment_tool.backend()}; headlines at or below "
            f"{negative_cutoff:+.2f} are treated as negative.",
            holding["name"],
            trail=[
                _step("What was detected", f'A headline that names {holding["name"]}: "{item["title"]}" '
                                           f'({item.get("source") or "news"}).',
                      "Google News search for your holdings over the last 3 days. A headline is kept only if it "
                      "names the holding."),
                _step("Why it is an alert",
                      f"{sentiment_tool.backend()} scored it {sentiment:+.2f} on a scale from -1 (negative) to +1 "
                      f"(positive). A score of {negative_cutoff:+.2f} or lower counts as negative.",
                      _sentiment_record()),
                _step("Has the price reacted", reaction, ABNORMAL_METHOD) if reaction else None,
                _impact_step(score),
            ],
        ))
    return alerts


def _market_alert(total: float | None = None, beta: float | None = None) -> list[dict]:
    from app.agents.nodes import _macro_flags

    indicators, _ = get_macro()
    flags = _macro_flags(indicators)
    if not flags:
        return []
    caution = ("Sudden moves in individual holdings are more likely in stressed markets. Avoid large new "
               "positions until conditions settle.")
    if total and beta:
        vix = next((i["value"] for i in indicators if i["ticker"] == "^INDIAVIX"), None)
        solution = solutions.index_hedge(total, beta, vix, "Hold off large new purchases; hedge the index only "
                                                           "if you expect more", caution)
    else:
        solution = solutions.solution(
            "watch", "Hold off large new purchases", [caution],
            why="Rule: market stress is a reason for caution, not for selling. No hedge is sized because the "
                "portfolio could not be valued.")
    return [_alert(
        "info", "market", ",".join(flags),
        "Market stress: " + ", ".join(flags),
        "; ".join(f'{i["label"]} {i["value"]:,.2f} ({i["change_1m_pct"]:+.1f}% in a month)' for i in indicators) + ".",
        solution,
        "Yahoo Finance; flags are fixed thresholds on the one-month changes.",
        trail=[
            _step("What was detected",
                  "; ".join(f'{i["label"]} {i["value"]:,.2f}, {i["change_1m_pct"]:+.1f}% in a month' for i in indicators)
                  + ".", "Yahoo Finance closing levels and their change over 21 sessions."),
            _step("Why it is an alert",
                  f"Stress flags raised: {', '.join(flags)}. A flag is raised when India VIX is at 20 or up 20% in a "
                  f"month, the Nifty 50 is down 5% in a month, Brent is up 10%, or USD/INR is up 2%."),
        ],
    )]


# --------------------------------------------------------------------------- entry point


def _alt_data_alerts(positions: list[dict], closes, scenario: str | None) -> list[dict]:
    """Weather and geopolitical signals with exposure, pricing and a sized hedge."""
    alerts = []
    for a in radar_alerts(positions, closes, scenario):
        parts, drill = a["parts"], a["hedge"]["drill"]
        reach = ("Company assets within 300 km of the site: power stations from the WRI plant database and a "
                 "curated list of refineries, ports and plants." if parts["kind"] == "weather" else
                 "Holdings whose price history covers at least two past events of this kind.")
        priced = ("Not measured: a drill has no real market reaction." if parts["priced"] is None else
                  f"About {parts['priced'] * 100:.0f}% of the expected loss, judging by how the exposed holdings "
                  f"moved beyond the market over the last {PRICED_SESSIONS} sessions.")
        alerts.append(_alert(
            a["severity"], a["category"], a["key"], a["title"], a["detail"],
            solutions.from_hedge(a["hedge"]), a["basis"], hedge=a["hedge"], recommendation=a["recommendation"],
            trail=[
                _step("What was detected", parts["signal"],
                      None if drill else "; ".join(parts["sources"])),
                _step("Which holdings it reaches",
                      f'{parts["exposed"]}.' if parts["exposed"] else "None of your holdings.", reach),
                _step("What similar events did", parts["moves"]),
                _step("How much is already in the price", priced),
                _step("How far to trust the signal",
                      "This is a rehearsal, so there is nothing to corroborate." if drill else
                      f'Confidence {parts["confidence"].lower()}: {len(parts["sources"])} independent '
                      f'source{"s" if len(parts["sources"]) != 1 else ""} ({"; ".join(parts["sources"])}). Three or '
                      f"more is high, two is medium, one is low."),
            ],
        ))
    return alerts


def _risk_ranking(positions: list[dict], scores: dict | None, total: float) -> list[dict]:
    """Every scored holding, largest rupee downside first."""
    rows = [
        {"name": p["name"], "weight": round(p["value"] / total, 4), "fall": round(scores[p["ticker"]]["fall"], 3),
         "elevated": scores[p["ticker"]]["elevated"],
         "downside": round(scores[p["ticker"]]["downside"], 4),
         "usual_downside": round(scores[p["ticker"]]["usual_downside"], 4),
         "downside_amount": round(-scores[p["ticker"]]["downside"] * p["value"])}
        for p in positions if p["ticker"] in (scores or {})
    ]
    return sorted(rows, key=lambda r: -r["downside_amount"])


def build_alerts(raw_holdings: list[dict] | None, scenario: str | None = None) -> dict:
    holdings, source = normalise_holdings(raw_holdings)
    closes, price_source = get_history([h["ticker"] for h in holdings])
    alerts: list[dict] = []
    unavailable: list[str] = []
    as_of = None
    total = beta = scores = None
    ranking: list[dict] = []

    if closes is None:
        unavailable.append("prices")
    else:
        latest = closes.iloc[-1]
        positions = []
        for h in holdings:
            price = latest.get(h["ticker"])
            if price is not None and not math.isnan(price):
                positions.append({**h, "price": float(price), "value": float(price) * h["units"]})
        positions.sort(key=lambda p: -p["value"])
        total = sum(p["value"] for p in positions)
        as_of = closes.index[-1].date().isoformat()
        if total > 0:
            returns = metrics.daily_returns(closes)
            betas = {p["ticker"]: metrics.beta(returns[p["ticker"]], returns[NIFTY]) for p in positions}
            known = {t: b for t, b in betas.items() if b is not None}
            beta = sum(known[p["ticker"]] * p["value"] / total for p in positions if p["ticker"] in known) or None
            today = _today(positions, closes)
            try:
                scores = impact.score_positions(positions, closes)
            except Exception:
                scores = None
            if scores is None:
                unavailable.append("impact model (macro data missing; the price-only risk model was used)")
            ranking = _risk_ranking(positions, scores, total)
            try:
                vix = next((i["value"] for i in get_macro()[0] if i["ticker"] == "^INDIAVIX"), None)
            except Exception:
                vix = None
            for build in (lambda: _alt_data_alerts(positions, closes, scenario),
                          lambda: _portfolio_alert(positions, closes, total, returns, beta, vix),
                          lambda: _price_alerts(positions, closes, total, today, scores, returns),
                          lambda: _concentration_alert(positions, total, returns),
                          lambda: _news_alerts(positions, today, scores, returns, total)):
                try:
                    alerts += build()
                except Exception:  # one failing check must not hide the others
                    unavailable.append("a check failed")

    try:
        alerts += _market_alert(total, beta)
    except Exception:
        unavailable.append("market")

    # A drill is something the user just asked to see, so it leads; then most severe first.
    alerts.sort(key=lambda a: (not (a["hedge"] or {}).get("drill", False), SEVERITY_ORDER[a["severity"]]))
    shock = _trained("shock_model")
    return {
        "alerts": alerts,
        "risk_ranking": ranking,
        "portfolio_source": source,
        "prices_as_of": as_of,
        "price_source": price_source,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "unavailable": sorted(set(unavailable)),
        "risk_model": impact.summary() if scores is not None else (
            {"name": "Price-only logistic model", "auc": shock["test"]["auc"], "tested_on": shock["test"]["period"],
             "trained_on": shock["trained_on"]} if shock else None),
    }
